### ISSUE TITLE
C and C++ versions

### ISSUE THREAD

**Issue by Daniel-Boll** [awnion/parallel_fibonacci#1]
Hello @awnion, I'd like to contribute, I don't if you are actually accepting contributions but I'm trying to implement in C with OpenMP

![image](https://user-images.githubusercontent.com/43689101/170786544-b22c5993-f8b6-43bc-9021-36cf8756cda5.png)

Currently not done yet, but the parallel function does have to be recursive?

Best regards,
Daniel Boll. :flower_playing_cards:

**Comment by awnion** [comment]
Fully up to you. Just burn the cores.

In my case I want to showcase sort of naïve implementations in different languages. I made it recursive just because it's easier to make it clean, but it's not a restriction at all.

**Comment by awnion** [comment]
So it **shouldn't** be the only one implementation per language. The More implementations/ideas the better.

**Comment by Daniel-Boll** [comment]
![image](https://user-images.githubusercontent.com/43689101/170797698-a1c0578b-09c2-443b-9b73-3842bb8d3824.png)

My results aren't faster, should the result be? It can burn the cores, just is not being fast

**Comment by awnion** [comment]
> ![image](https://user-images.githubusercontent.com/43689101/170797698-a1c0578b-09c2-443b-9b73-3842bb8d3824.png)
> 
> My results aren't faster, should the result be? It can burn the cores, just is not being fast

well... parallel code should be faster than single core isn't it? ;) Unless what's the point?

and BTW you can make your own fork, so I might look at it time to time and may suggest you something if you don't mind ofc
